name: build

on: [push, pull_request]

jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #ubuntu
        build: [windows,macos,ubuntu]
        include:
          - build: macos
            os: macos-latest
            SKIP_LIGHTGBM: True
          - build: ubuntu
            os: ubuntu-latest
            SKIP_LIGHTGBM: False
          - build: windows
            os: windows-latest
            SKIP_LIGHTGBM: False
        python-version: ["3.8","3.9","3.10"]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        pip3 install --upgrade setuptools pip
        pip3 install ".[all]"
        
    - name: Test with pytest
      run: pytest -vs test/
        
    